name: Main CI

on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry add sqlfluff

      - name: Install project
        run: |
          poetry install

      - name: Install sqlfluff
        run: |
          poetry run pip install sqlfluff

      - name: Run linters and formatters
        run: |
          poetry run black ./src
          poetry run mypy ./src
          poetry run coverage run -m pytest .
          poetry run coverage html
          poetry run ruff check --fix .
          

      - name: Run tests
        run: |
          poetry run coverage run -m pytest .

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

      - name: Post test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results
